import { BlenderGeometry } from '../core/Geometry';

import boxConfig from '../blender/raw/box.json';
import squareConfig from '../blender/raw/square.json';
import tree001Config from '../blender/raw/tree_001.json';
import tree002Config from '../blender/raw/tree_002.json';
import tree003Config from '../blender/raw/tree_003.json';
import trunkConfig from '../blender/raw/trunk.json';
import rockConfig from '../blender/raw/rock.json';
import bushConfig from '../blender/raw/bush.json';
import grassConfig from '../blender/raw/grass.json';
import playerHandsConfig from '../blender/raw/player_hands.json';
import playerBodyConfig from '../blender/raw/player_body.json';
import playerRingFrontConfig from '../blender/raw/player_ring_front.json';
import playerRingBackConfig from '../blender/raw/player_ring_back.json';
import playerFaceConfig from '../blender/raw/player_face.json';
import streamFullConfig from '../blender/raw/stream_full.json';
import streamSideConfig from '../blender/raw/stream_side.json';
import streamCornerConfig from '../blender/raw/stream_corner.json';

export const tree001 = new BlenderGeometry(tree001Config, { name: 'tree_001' });
export const tree002 = new BlenderGeometry(tree002Config, { name: 'tree_002' });
export const tree003 = new BlenderGeometry(tree003Config, { name: 'tree_003' });
export const trunk = new BlenderGeometry(trunkConfig, { name: 'trunk' });
export const box = new BlenderGeometry(boxConfig, { name: 'box' });
export const square = new BlenderGeometry(squareConfig, { name: 'square' });
export const rock = new BlenderGeometry(rockConfig, { name: 'rock' });
export const bush = new BlenderGeometry(bushConfig, { name: 'bush' });
export const grass = new BlenderGeometry(grassConfig, { name: 'grass' });
export const playerHands = new BlenderGeometry(playerHandsConfig);
export const playerRingFront = new BlenderGeometry(playerRingFrontConfig);
export const playerRingBack = new BlenderGeometry(playerRingBackConfig);
export const playerBody = new BlenderGeometry(playerBodyConfig);
export const playerFace = new BlenderGeometry(playerFaceConfig);
export const streamFull = new BlenderGeometry(streamFullConfig);
export const streamSide = new BlenderGeometry(streamSideConfig);
export const streamCorner = new BlenderGeometry(streamCornerConfig);
